// Code generated by github.com/openfluke/webgpu/cmd/enums/regen.py; DO NOT EDIT.

package wgpu

type AdapterType uint32

const (
	AdapterTypeDiscreteGPU   AdapterType = 0x00000001
	AdapterTypeIntegratedGPU AdapterType = 0x00000002
	AdapterTypeCPU           AdapterType = 0x00000003
	AdapterTypeUnknown       AdapterType = 0x00000004
)

func (v AdapterType) String() string {
	switch v {
	case AdapterTypeDiscreteGPU:
		return "discrete-gpu"
	case AdapterTypeIntegratedGPU:
		return "integrated-gpu"
	case AdapterTypeCPU:
		return "cpu"
	case AdapterTypeUnknown:
		return "unknown"
	default:
		return ""
	}
}

type AddressMode uint32

const (
	AddressModeUndefined    AddressMode = 0x00000000
	AddressModeClampToEdge  AddressMode = 0x00000001
	AddressModeRepeat       AddressMode = 0x00000002
	AddressModeMirrorRepeat AddressMode = 0x00000003
)

func (v AddressMode) String() string {
	switch v {
	case AddressModeUndefined:
		return "undefined"
	case AddressModeClampToEdge:
		return "clamp-to-edge"
	case AddressModeRepeat:
		return "repeat"
	case AddressModeMirrorRepeat:
		return "mirror-repeat"
	default:
		return ""
	}
}

type BackendType uint32

const (
	BackendTypeUndefined BackendType = 0x00000000
	BackendTypeNull      BackendType = 0x00000001
	BackendTypeWebGPU    BackendType = 0x00000002
	BackendTypeD3D11     BackendType = 0x00000003
	BackendTypeD3D12     BackendType = 0x00000004
	BackendTypeMetal     BackendType = 0x00000005
	BackendTypeVulkan    BackendType = 0x00000006
	BackendTypeOpenGL    BackendType = 0x00000007
	BackendTypeOpenGLES  BackendType = 0x00000008
)

func (v BackendType) String() string {
	switch v {
	case BackendTypeUndefined:
		return "undefined"
	case BackendTypeNull:
		return "null"
	case BackendTypeWebGPU:
		return "web-gpu"
	case BackendTypeD3D11:
		return "d3d11"
	case BackendTypeD3D12:
		return "d3d12"
	case BackendTypeMetal:
		return "metal"
	case BackendTypeVulkan:
		return "vulkan"
	case BackendTypeOpenGL:
		return "open-gl"
	case BackendTypeOpenGLES:
		return "open-gles"
	default:
		return ""
	}
}

type BlendFactor uint32

const (
	BlendFactorUndefined         BlendFactor = 0x00000000
	BlendFactorZero              BlendFactor = 0x00000001
	BlendFactorOne               BlendFactor = 0x00000002
	BlendFactorSrc               BlendFactor = 0x00000003
	BlendFactorOneMinusSrc       BlendFactor = 0x00000004
	BlendFactorSrcAlpha          BlendFactor = 0x00000005
	BlendFactorOneMinusSrcAlpha  BlendFactor = 0x00000006
	BlendFactorDst               BlendFactor = 0x00000007
	BlendFactorOneMinusDst       BlendFactor = 0x00000008
	BlendFactorDstAlpha          BlendFactor = 0x00000009
	BlendFactorOneMinusDstAlpha  BlendFactor = 0x0000000A
	BlendFactorSrcAlphaSaturated BlendFactor = 0x0000000B
	BlendFactorConstant          BlendFactor = 0x0000000C
	BlendFactorOneMinusConstant  BlendFactor = 0x0000000D
	BlendFactorSrc1              BlendFactor = 0x0000000E
	BlendFactorOneMinusSrc1      BlendFactor = 0x0000000F
	BlendFactorSrc1Alpha         BlendFactor = 0x00000010
	BlendFactorOneMinusSrc1Alpha BlendFactor = 0x00000011
)

func (v BlendFactor) String() string {
	switch v {
	case BlendFactorUndefined:
		return "undefined"
	case BlendFactorZero:
		return "zero"
	case BlendFactorOne:
		return "one"
	case BlendFactorSrc:
		return "src"
	case BlendFactorOneMinusSrc:
		return "one-minus-src"
	case BlendFactorSrcAlpha:
		return "src-alpha"
	case BlendFactorOneMinusSrcAlpha:
		return "one-minus-src-alpha"
	case BlendFactorDst:
		return "dst"
	case BlendFactorOneMinusDst:
		return "one-minus-dst"
	case BlendFactorDstAlpha:
		return "dst-alpha"
	case BlendFactorOneMinusDstAlpha:
		return "one-minus-dst-alpha"
	case BlendFactorSrcAlphaSaturated:
		return "src-alpha-saturated"
	case BlendFactorConstant:
		return "constant"
	case BlendFactorOneMinusConstant:
		return "one-minus-constant"
	case BlendFactorSrc1:
		return "src1"
	case BlendFactorOneMinusSrc1:
		return "one-minus-src1"
	case BlendFactorSrc1Alpha:
		return "src1-alpha"
	case BlendFactorOneMinusSrc1Alpha:
		return "one-minus-src1-alpha"
	default:
		return ""
	}
}

type BlendOperation uint32

const (
	BlendOperationUndefined       BlendOperation = 0x00000000
	BlendOperationAdd             BlendOperation = 0x00000001
	BlendOperationSubtract        BlendOperation = 0x00000002
	BlendOperationReverseSubtract BlendOperation = 0x00000003
	BlendOperationMin             BlendOperation = 0x00000004
	BlendOperationMax             BlendOperation = 0x00000005
)

func (v BlendOperation) String() string {
	switch v {
	case BlendOperationUndefined:
		return "undefined"
	case BlendOperationAdd:
		return "add"
	case BlendOperationSubtract:
		return "subtract"
	case BlendOperationReverseSubtract:
		return "reverse-subtract"
	case BlendOperationMin:
		return "min"
	case BlendOperationMax:
		return "max"
	default:
		return ""
	}
}

type BufferBindingType uint32

const (
	BufferBindingTypeBindingNotUsed  BufferBindingType = 0x00000000
	BufferBindingTypeUndefined       BufferBindingType = 0x00000001
	BufferBindingTypeUniform         BufferBindingType = 0x00000002
	BufferBindingTypeStorage         BufferBindingType = 0x00000003
	BufferBindingTypeReadOnlyStorage BufferBindingType = 0x00000004
)

func (v BufferBindingType) String() string {
	switch v {
	case BufferBindingTypeBindingNotUsed:
		return "binding-not-used"
	case BufferBindingTypeUndefined:
		return "undefined"
	case BufferBindingTypeUniform:
		return "uniform"
	case BufferBindingTypeStorage:
		return "storage"
	case BufferBindingTypeReadOnlyStorage:
		return "read-only-storage"
	default:
		return ""
	}
}

type BufferMapState uint32

const (
	BufferMapStateUnmapped BufferMapState = 0x00000001
	BufferMapStatePending  BufferMapState = 0x00000002
	BufferMapStateMapped   BufferMapState = 0x00000003
)

func (v BufferMapState) String() string {
	switch v {
	case BufferMapStateUnmapped:
		return "unmapped"
	case BufferMapStatePending:
		return "pending"
	case BufferMapStateMapped:
		return "mapped"
	default:
		return ""
	}
}

type BufferUsage uint32

const (
	BufferUsageNone         BufferUsage = 0x00000000
	BufferUsageMapRead      BufferUsage = 0x00000001
	BufferUsageMapWrite     BufferUsage = 0x00000002
	BufferUsageCopySrc      BufferUsage = 0x00000004
	BufferUsageCopyDst      BufferUsage = 0x00000008
	BufferUsageIndex        BufferUsage = 0x00000010
	BufferUsageVertex       BufferUsage = 0x00000020
	BufferUsageUniform      BufferUsage = 0x00000040
	BufferUsageStorage      BufferUsage = 0x00000080
	BufferUsageIndirect     BufferUsage = 0x00000100
	BufferUsageQueryResolve BufferUsage = 0x00000200
)

func (v BufferUsage) String() string {
	switch v {
	case BufferUsageNone:
		return "none"
	case BufferUsageMapRead:
		return "map-read"
	case BufferUsageMapWrite:
		return "map-write"
	case BufferUsageCopySrc:
		return "copy-src"
	case BufferUsageCopyDst:
		return "copy-dst"
	case BufferUsageIndex:
		return "index"
	case BufferUsageVertex:
		return "vertex"
	case BufferUsageUniform:
		return "uniform"
	case BufferUsageStorage:
		return "storage"
	case BufferUsageIndirect:
		return "indirect"
	case BufferUsageQueryResolve:
		return "query-resolve"
	default:
		return ""
	}
}

type CallbackMode uint32

const (
	CallbackModeWaitAnyOnly        CallbackMode = 0x00000001
	CallbackModeAllowProcessEvents CallbackMode = 0x00000002
	CallbackModeAllowSpontaneous   CallbackMode = 0x00000003
)

func (v CallbackMode) String() string {
	switch v {
	case CallbackModeWaitAnyOnly:
		return "wait-any-only"
	case CallbackModeAllowProcessEvents:
		return "allow-process-events"
	case CallbackModeAllowSpontaneous:
		return "allow-spontaneous"
	default:
		return ""
	}
}

type ColorWriteMask uint32

const (
	ColorWriteMaskNone  ColorWriteMask = 0x00000000
	ColorWriteMaskRed   ColorWriteMask = 0x00000001
	ColorWriteMaskGreen ColorWriteMask = 0x00000002
	ColorWriteMaskBlue  ColorWriteMask = 0x00000004
	ColorWriteMaskAlpha ColorWriteMask = 0x00000008
	ColorWriteMaskAll   ColorWriteMask = 0x0000000F
)

func (v ColorWriteMask) String() string {
	switch v {
	case ColorWriteMaskNone:
		return "none"
	case ColorWriteMaskRed:
		return "red"
	case ColorWriteMaskGreen:
		return "green"
	case ColorWriteMaskBlue:
		return "blue"
	case ColorWriteMaskAlpha:
		return "alpha"
	case ColorWriteMaskAll:
		return "all"
	default:
		return ""
	}
}

type CompareFunction uint32

const (
	CompareFunctionUndefined    CompareFunction = 0x00000000
	CompareFunctionNever        CompareFunction = 0x00000001
	CompareFunctionLess         CompareFunction = 0x00000002
	CompareFunctionEqual        CompareFunction = 0x00000003
	CompareFunctionLessEqual    CompareFunction = 0x00000004
	CompareFunctionGreater      CompareFunction = 0x00000005
	CompareFunctionNotEqual     CompareFunction = 0x00000006
	CompareFunctionGreaterEqual CompareFunction = 0x00000007
	CompareFunctionAlways       CompareFunction = 0x00000008
)

func (v CompareFunction) String() string {
	switch v {
	case CompareFunctionUndefined:
		return "undefined"
	case CompareFunctionNever:
		return "never"
	case CompareFunctionLess:
		return "less"
	case CompareFunctionEqual:
		return "equal"
	case CompareFunctionLessEqual:
		return "less-equal"
	case CompareFunctionGreater:
		return "greater"
	case CompareFunctionNotEqual:
		return "not-equal"
	case CompareFunctionGreaterEqual:
		return "greater-equal"
	case CompareFunctionAlways:
		return "always"
	default:
		return ""
	}
}

type CompilationInfoRequestStatus uint32

const (
	CompilationInfoRequestStatusSuccess           CompilationInfoRequestStatus = 0x00000001
	CompilationInfoRequestStatusCallbackCancelled CompilationInfoRequestStatus = 0x00000002
)

func (v CompilationInfoRequestStatus) String() string {
	switch v {
	case CompilationInfoRequestStatusSuccess:
		return "success"
	case CompilationInfoRequestStatusCallbackCancelled:
		return "callback-cancelled"
	default:
		return ""
	}
}

type CompilationMessageType uint32

const (
	CompilationMessageTypeError   CompilationMessageType = 0x00000001
	CompilationMessageTypeWarning CompilationMessageType = 0x00000002
	CompilationMessageTypeInfo    CompilationMessageType = 0x00000003
)

func (v CompilationMessageType) String() string {
	switch v {
	case CompilationMessageTypeError:
		return "error"
	case CompilationMessageTypeWarning:
		return "warning"
	case CompilationMessageTypeInfo:
		return "info"
	default:
		return ""
	}
}

type ComponentSwizzle uint32

const (
	ComponentSwizzleUndefined ComponentSwizzle = 0x00000000
	ComponentSwizzleZero      ComponentSwizzle = 0x00000001
	ComponentSwizzleOne       ComponentSwizzle = 0x00000002
	ComponentSwizzleR         ComponentSwizzle = 0x00000003
	ComponentSwizzleG         ComponentSwizzle = 0x00000004
	ComponentSwizzleB         ComponentSwizzle = 0x00000005
	ComponentSwizzleA         ComponentSwizzle = 0x00000006
)

func (v ComponentSwizzle) String() string {
	switch v {
	case ComponentSwizzleUndefined:
		return "undefined"
	case ComponentSwizzleZero:
		return "zero"
	case ComponentSwizzleOne:
		return "one"
	case ComponentSwizzleR:
		return "r"
	case ComponentSwizzleG:
		return "g"
	case ComponentSwizzleB:
		return "b"
	case ComponentSwizzleA:
		return "a"
	default:
		return ""
	}
}

type CompositeAlphaMode uint32

const (
	CompositeAlphaModeAuto            CompositeAlphaMode = 0x00000000
	CompositeAlphaModeOpaque          CompositeAlphaMode = 0x00000001
	CompositeAlphaModePremultiplied   CompositeAlphaMode = 0x00000002
	CompositeAlphaModeUnpremultiplied CompositeAlphaMode = 0x00000003
	CompositeAlphaModeInherit         CompositeAlphaMode = 0x00000004
)

func (v CompositeAlphaMode) String() string {
	switch v {
	case CompositeAlphaModeAuto:
		return "auto"
	case CompositeAlphaModeOpaque:
		return "opaque"
	case CompositeAlphaModePremultiplied:
		return "premultiplied"
	case CompositeAlphaModeUnpremultiplied:
		return "unpremultiplied"
	case CompositeAlphaModeInherit:
		return "inherit"
	default:
		return ""
	}
}

type CreatePipelineAsyncStatus uint32

const (
	CreatePipelineAsyncStatusSuccess           CreatePipelineAsyncStatus = 0x00000001
	CreatePipelineAsyncStatusCallbackCancelled CreatePipelineAsyncStatus = 0x00000002
	CreatePipelineAsyncStatusValidationError   CreatePipelineAsyncStatus = 0x00000003
	CreatePipelineAsyncStatusInternalError     CreatePipelineAsyncStatus = 0x00000004
)

func (v CreatePipelineAsyncStatus) String() string {
	switch v {
	case CreatePipelineAsyncStatusSuccess:
		return "success"
	case CreatePipelineAsyncStatusCallbackCancelled:
		return "callback-cancelled"
	case CreatePipelineAsyncStatusValidationError:
		return "validation-error"
	case CreatePipelineAsyncStatusInternalError:
		return "internal-error"
	default:
		return ""
	}
}

type CullMode uint32

const (
	CullModeUndefined CullMode = 0x00000000
	CullModeNone      CullMode = 0x00000001
	CullModeFront     CullMode = 0x00000002
	CullModeBack      CullMode = 0x00000003
)

func (v CullMode) String() string {
	switch v {
	case CullModeUndefined:
		return "undefined"
	case CullModeNone:
		return "none"
	case CullModeFront:
		return "front"
	case CullModeBack:
		return "back"
	default:
		return ""
	}
}

type DeviceLostReason uint32

const (
	DeviceLostReasonUnknown           DeviceLostReason = 0x00000001
	DeviceLostReasonDestroyed         DeviceLostReason = 0x00000002
	DeviceLostReasonCallbackCancelled DeviceLostReason = 0x00000003
	DeviceLostReasonFailedCreation    DeviceLostReason = 0x00000004
)

func (v DeviceLostReason) String() string {
	switch v {
	case DeviceLostReasonUnknown:
		return "unknown"
	case DeviceLostReasonDestroyed:
		return "destroyed"
	case DeviceLostReasonCallbackCancelled:
		return "callback-cancelled"
	case DeviceLostReasonFailedCreation:
		return "failed-creation"
	default:
		return ""
	}
}

type Dx12Compiler uint32

const (
	Dx12CompilerUndefined Dx12Compiler = 0x00000000
	Dx12CompilerFxc       Dx12Compiler = 0x00000001
	Dx12CompilerDxc       Dx12Compiler = 0x00000002
)

func (v Dx12Compiler) String() string {
	switch v {
	case Dx12CompilerUndefined:
		return "undefined"
	case Dx12CompilerFxc:
		return "fxc"
	case Dx12CompilerDxc:
		return "dxc"
	default:
		return ""
	}
}

type Dx12SwapchainKind uint32

const (
	Dx12SwapchainKindUndefined      Dx12SwapchainKind = 0x00000000
	Dx12SwapchainKindDxgiFromHwnd   Dx12SwapchainKind = 0x00000001
	Dx12SwapchainKindDxgiFromVisual Dx12SwapchainKind = 0x00000002
)

func (v Dx12SwapchainKind) String() string {
	switch v {
	case Dx12SwapchainKindUndefined:
		return "undefined"
	case Dx12SwapchainKindDxgiFromHwnd:
		return "dxgi-from-hwnd"
	case Dx12SwapchainKindDxgiFromVisual:
		return "dxgi-from-visual"
	default:
		return ""
	}
}

type DxcMaxShaderModel uint32

const (
	DxcMaxShaderModelV60 DxcMaxShaderModel = 0x00000000
	DxcMaxShaderModelV61 DxcMaxShaderModel = 0x00000001
	DxcMaxShaderModelV62 DxcMaxShaderModel = 0x00000002
	DxcMaxShaderModelV63 DxcMaxShaderModel = 0x00000003
	DxcMaxShaderModelV64 DxcMaxShaderModel = 0x00000004
	DxcMaxShaderModelV65 DxcMaxShaderModel = 0x00000005
	DxcMaxShaderModelV66 DxcMaxShaderModel = 0x00000006
	DxcMaxShaderModelV67 DxcMaxShaderModel = 0x00000007
)

func (v DxcMaxShaderModel) String() string {
	switch v {
	case DxcMaxShaderModelV60:
		return "v60"
	case DxcMaxShaderModelV61:
		return "v61"
	case DxcMaxShaderModelV62:
		return "v62"
	case DxcMaxShaderModelV63:
		return "v63"
	case DxcMaxShaderModelV64:
		return "v64"
	case DxcMaxShaderModelV65:
		return "v65"
	case DxcMaxShaderModelV66:
		return "v66"
	case DxcMaxShaderModelV67:
		return "v67"
	default:
		return ""
	}
}

type ErrorFilter uint32

const (
	ErrorFilterValidation  ErrorFilter = 0x00000001
	ErrorFilterOutOfMemory ErrorFilter = 0x00000002
	ErrorFilterInternal    ErrorFilter = 0x00000003
)

func (v ErrorFilter) String() string {
	switch v {
	case ErrorFilterValidation:
		return "validation"
	case ErrorFilterOutOfMemory:
		return "out-of-memory"
	case ErrorFilterInternal:
		return "internal"
	default:
		return ""
	}
}

type ErrorType uint32

const (
	ErrorTypeNoError     ErrorType = 0x00000001
	ErrorTypeValidation  ErrorType = 0x00000002
	ErrorTypeOutOfMemory ErrorType = 0x00000003
	ErrorTypeInternal    ErrorType = 0x00000004
	ErrorTypeUnknown     ErrorType = 0x00000005
)

func (v ErrorType) String() string {
	switch v {
	case ErrorTypeNoError:
		return "no-error"
	case ErrorTypeValidation:
		return "validation"
	case ErrorTypeOutOfMemory:
		return "out-of-memory"
	case ErrorTypeInternal:
		return "internal"
	case ErrorTypeUnknown:
		return "unknown"
	default:
		return "unknown"
	}
}

type FeatureLevel uint32

const (
	FeatureLevelUndefined     FeatureLevel = 0x00000000
	FeatureLevelCompatibility FeatureLevel = 0x00000001
	FeatureLevelCore          FeatureLevel = 0x00000002
)

func (v FeatureLevel) String() string {
	switch v {
	case FeatureLevelUndefined:
		return "undefined"
	case FeatureLevelCompatibility:
		return "compatibility"
	case FeatureLevelCore:
		return "core"
	default:
		return ""
	}
}

type FeatureName uint32

const (
	FeatureNameCoreFeaturesAndLimits                                 FeatureName = 0x00000001
	FeatureNameDepthClipControl                                      FeatureName = 0x00000002
	FeatureNameDepth32FloatStencil8                                  FeatureName = 0x00000003
	FeatureNameTextureCompressionBC                                  FeatureName = 0x00000004
	FeatureNameTextureCompressionBCSliced3D                          FeatureName = 0x00000005
	FeatureNameTextureCompressionETC2                                FeatureName = 0x00000006
	FeatureNameTextureCompressionASTC                                FeatureName = 0x00000007
	FeatureNameTextureCompressionASTCSliced3D                        FeatureName = 0x00000008
	FeatureNameTimestampQuery                                        FeatureName = 0x00000009
	FeatureNameIndirectFirstInstance                                 FeatureName = 0x0000000A
	FeatureNameShaderF16                                             FeatureName = 0x0000000B
	FeatureNameRG11B10UfloatRenderable                               FeatureName = 0x0000000C
	FeatureNameBGRA8UnormStorage                                     FeatureName = 0x0000000D
	FeatureNameFloat32Filterable                                     FeatureName = 0x0000000E
	FeatureNameFloat32Blendable                                      FeatureName = 0x0000000F
	FeatureNameClipDistances                                         FeatureName = 0x00000010
	FeatureNameDualSourceBlending                                    FeatureName = 0x00000011
	FeatureNameSubgroups                                             FeatureName = 0x00000012
	FeatureNameTextureFormatsTier1                                   FeatureName = 0x00000013
	FeatureNameTextureFormatsTier2                                   FeatureName = 0x00000014
	FeatureNamePrimitiveIndex                                        FeatureName = 0x00000015
	FeatureNameTextureComponentSwizzle                               FeatureName = 0x00000016
	FeatureNameImmediates                                            FeatureName = 0x00030001
	FeatureNameTextureAdapterSpecificFormatFeatures                  FeatureName = 0x00030002
	FeatureNameMultiDrawIndirectCount                                FeatureName = 0x00030004
	FeatureNameVertexWritableStorage                                 FeatureName = 0x00030005
	FeatureNameTextureBindingArray                                   FeatureName = 0x00030006
	FeatureNameSampledTextureAndStorageBufferArrayNonUniformIndexing FeatureName = 0x00030007
	FeatureNamePipelineStatisticsQuery                               FeatureName = 0x00030008
	FeatureNameStorageResourceBindingArray                           FeatureName = 0x00030009
	FeatureNamePartiallyBoundBindingArray                            FeatureName = 0x0003000A
	FeatureNameTextureFormat16bitNorm                                FeatureName = 0x0003000B
	FeatureNameTextureCompressionAstcHdr                             FeatureName = 0x0003000C
	FeatureNameMappablePrimaryBuffers                                FeatureName = 0x0003000E
	FeatureNameBufferBindingArray                                    FeatureName = 0x0003000F
	FeatureNameUniformBufferAndStorageTextureArrayNonUniformIndexing FeatureName = 0x00030010
	FeatureNamePolygonModeLine                                       FeatureName = 0x00030013
	FeatureNamePolygonModePoint                                      FeatureName = 0x00030014
	FeatureNameConservativeRasterization                             FeatureName = 0x00030015
	FeatureNameSpirvShaderPassthrough                                FeatureName = 0x00030017
	FeatureNameVertexAttribute64bit                                  FeatureName = 0x00030019
	FeatureNameTextureFormatNv12                                     FeatureName = 0x0003001A
	FeatureNameRayQuery                                              FeatureName = 0x0003001C
	FeatureNameShaderF64                                             FeatureName = 0x0003001D
	FeatureNameShaderI16                                             FeatureName = 0x0003001E
	FeatureNameShaderEarlyDepthTest                                  FeatureName = 0x00030020
	FeatureNameSubgroup                                              FeatureName = 0x00030021
	FeatureNameSubgroupVertex                                        FeatureName = 0x00030022
	FeatureNameSubgroupBarrier                                       FeatureName = 0x00030023
	FeatureNameTimestampQueryInsideEncoders                          FeatureName = 0x00030024
	FeatureNameTimestampQueryInsidePasses                            FeatureName = 0x00030025
	FeatureNameShaderInt64                                           FeatureName = 0x00030026
)

func (v FeatureName) String() string {
	switch v {
	case FeatureNameCoreFeaturesAndLimits:
		return "core-features-and-limits"
	case FeatureNameDepthClipControl:
		return "depth-clip-control"
	case FeatureNameDepth32FloatStencil8:
		return "depth32-float-stencil8"
	case FeatureNameTextureCompressionBC:
		return "texture-compression-bc"
	case FeatureNameTextureCompressionBCSliced3D:
		return "texture-compression-bc-sliced3d"
	case FeatureNameTextureCompressionETC2:
		return "texture-compression-etc2"
	case FeatureNameTextureCompressionASTC:
		return "texture-compression-astc"
	case FeatureNameTextureCompressionASTCSliced3D:
		return "texture-compression-astc-sliced3d"
	case FeatureNameTimestampQuery:
		return "timestamp-query"
	case FeatureNameIndirectFirstInstance:
		return "indirect-first-instance"
	case FeatureNameShaderF16:
		return "shader-f16"
	case FeatureNameRG11B10UfloatRenderable:
		return "rg11b10-ufloat-renderable"
	case FeatureNameBGRA8UnormStorage:
		return "bgra8-unorm-storage"
	case FeatureNameFloat32Filterable:
		return "float32-filterable"
	case FeatureNameFloat32Blendable:
		return "float32-blendable"
	case FeatureNameClipDistances:
		return "clip-distances"
	case FeatureNameDualSourceBlending:
		return "dual-source-blending"
	case FeatureNameSubgroups:
		return "subgroups"
	case FeatureNameTextureFormatsTier1:
		return "texture-formats-tier1"
	case FeatureNameTextureFormatsTier2:
		return "texture-formats-tier2"
	case FeatureNamePrimitiveIndex:
		return "primitive-index"
	case FeatureNameTextureComponentSwizzle:
		return "texture-component-swizzle"
	case FeatureNameImmediates:
		return "immediates"
	case FeatureNameTextureAdapterSpecificFormatFeatures:
		return "texture-adapter-specific-format-features"
	case FeatureNameMultiDrawIndirectCount:
		return "multi-draw-indirect-count"
	case FeatureNameVertexWritableStorage:
		return "vertex-writable-storage"
	case FeatureNameTextureBindingArray:
		return "texture-binding-array"
	case FeatureNameSampledTextureAndStorageBufferArrayNonUniformIndexing:
		return "sampled-texture-and-storage-buffer-array-non-uniform-indexing"
	case FeatureNamePipelineStatisticsQuery:
		return "pipeline-statistics-query"
	case FeatureNameStorageResourceBindingArray:
		return "storage-resource-binding-array"
	case FeatureNamePartiallyBoundBindingArray:
		return "partially-bound-binding-array"
	case FeatureNameTextureFormat16bitNorm:
		return "texture-format16bit-norm"
	case FeatureNameTextureCompressionAstcHdr:
		return "texture-compression-astc-hdr"
	case FeatureNameMappablePrimaryBuffers:
		return "mappable-primary-buffers"
	case FeatureNameBufferBindingArray:
		return "buffer-binding-array"
	case FeatureNameUniformBufferAndStorageTextureArrayNonUniformIndexing:
		return "uniform-buffer-and-storage-texture-array-non-uniform-indexing"
	case FeatureNamePolygonModeLine:
		return "polygon-mode-line"
	case FeatureNamePolygonModePoint:
		return "polygon-mode-point"
	case FeatureNameConservativeRasterization:
		return "conservative-rasterization"
	case FeatureNameSpirvShaderPassthrough:
		return "spirv-shader-passthrough"
	case FeatureNameVertexAttribute64bit:
		return "vertex-attribute64bit"
	case FeatureNameTextureFormatNv12:
		return "texture-format-nv12"
	case FeatureNameRayQuery:
		return "ray-query"
	case FeatureNameShaderF64:
		return "shader-f64"
	case FeatureNameShaderI16:
		return "shader-i16"
	case FeatureNameShaderEarlyDepthTest:
		return "shader-early-depth-test"
	case FeatureNameSubgroup:
		return "subgroup"
	case FeatureNameSubgroupVertex:
		return "subgroup-vertex"
	case FeatureNameSubgroupBarrier:
		return "subgroup-barrier"
	case FeatureNameTimestampQueryInsideEncoders:
		return "timestamp-query-inside-encoders"
	case FeatureNameTimestampQueryInsidePasses:
		return "timestamp-query-inside-passes"
	case FeatureNameShaderInt64:
		return "shader-int64"
	default:
		return ""
	}
}

type FilterMode uint32

const (
	FilterModeUndefined FilterMode = 0x00000000
	FilterModeNearest   FilterMode = 0x00000001
	FilterModeLinear    FilterMode = 0x00000002
)

func (v FilterMode) String() string {
	switch v {
	case FilterModeUndefined:
		return "undefined"
	case FilterModeNearest:
		return "nearest"
	case FilterModeLinear:
		return "linear"
	default:
		return ""
	}
}

type FrontFace uint32

const (
	FrontFaceUndefined FrontFace = 0x00000000
	FrontFaceCCW       FrontFace = 0x00000001
	FrontFaceCW        FrontFace = 0x00000002
)

func (v FrontFace) String() string {
	switch v {
	case FrontFaceUndefined:
		return "undefined"
	case FrontFaceCCW:
		return "ccw"
	case FrontFaceCW:
		return "cw"
	default:
		return ""
	}
}

type GLFenceBehaviour uint32

const (
	GLFenceBehaviourNormal     GLFenceBehaviour = 0x00000000
	GLFenceBehaviourAutoFinish GLFenceBehaviour = 0x00000001
)

func (v GLFenceBehaviour) String() string {
	switch v {
	case GLFenceBehaviourNormal:
		return "normal"
	case GLFenceBehaviourAutoFinish:
		return "auto-finish"
	default:
		return ""
	}
}

type Gles3MinorVersion uint32

const (
	Gles3MinorVersionAutomatic Gles3MinorVersion = 0x00000000
	Gles3MinorVersionVersion0  Gles3MinorVersion = 0x00000001
	Gles3MinorVersionVersion1  Gles3MinorVersion = 0x00000002
	Gles3MinorVersionVersion2  Gles3MinorVersion = 0x00000003
)

func (v Gles3MinorVersion) String() string {
	switch v {
	case Gles3MinorVersionAutomatic:
		return "automatic"
	case Gles3MinorVersionVersion0:
		return "version0"
	case Gles3MinorVersionVersion1:
		return "version1"
	case Gles3MinorVersionVersion2:
		return "version2"
	default:
		return ""
	}
}

type IndexFormat uint32

const (
	IndexFormatUndefined IndexFormat = 0x00000000
	IndexFormatUint16    IndexFormat = 0x00000001
	IndexFormatUint32    IndexFormat = 0x00000002
)

func (v IndexFormat) String() string {
	switch v {
	case IndexFormatUndefined:
		return "undefined"
	case IndexFormatUint16:
		return "uint16"
	case IndexFormatUint32:
		return "uint32"
	default:
		return ""
	}
}

type InstanceBackend uint32

const (
	InstanceBackendAll           InstanceBackend = 0x00000000
	InstanceBackendVulkan        InstanceBackend = 0x00000001
	InstanceBackendGL            InstanceBackend = 0x00000002
	InstanceBackendSecondary     InstanceBackend = 0x00000002
	InstanceBackendMetal         InstanceBackend = 0x00000004
	InstanceBackendDX12          InstanceBackend = 0x00000008
	InstanceBackendBrowserWebGPU InstanceBackend = 0x00000020
	InstanceBackendPrimary       InstanceBackend = 0x0000002D
)

func (v InstanceBackend) String() string {
	switch v {
	case InstanceBackendAll:
		return "all"
	case InstanceBackendVulkan:
		return "vulkan"
	case InstanceBackendGL:
		return "gl"
	case InstanceBackendMetal:
		return "metal"
	case InstanceBackendDX12:
		return "dx12"
	case InstanceBackendBrowserWebGPU:
		return "browser-web-gpu"
	case InstanceBackendPrimary:
		return "primary"
	default:
		return ""
	}
}

type InstanceFeatureName uint32

const (
	InstanceFeatureNameTimedWaitAny              InstanceFeatureName = 0x00000001
	InstanceFeatureNameShaderSourceSPIRV         InstanceFeatureName = 0x00000002
	InstanceFeatureNameMultipleDevicesPerAdapter InstanceFeatureName = 0x00000003
)

func (v InstanceFeatureName) String() string {
	switch v {
	case InstanceFeatureNameTimedWaitAny:
		return "timed-wait-any"
	case InstanceFeatureNameShaderSourceSPIRV:
		return "shader-source-spirv"
	case InstanceFeatureNameMultipleDevicesPerAdapter:
		return "multiple-devices-per-adapter"
	default:
		return ""
	}
}

type InstanceFlag uint32

const (
	InstanceFlagEmpty                              InstanceFlag = 0x00000000
	InstanceFlagDebug                              InstanceFlag = 0x00000001
	InstanceFlagValidation                         InstanceFlag = 0x00000002
	InstanceFlagDiscardHalLabels                   InstanceFlag = 0x00000004
	InstanceFlagAllowUnderlyingNoncompliantAdapter InstanceFlag = 0x00000008
	InstanceFlagGPUBasedValidation                 InstanceFlag = 0x00000010
	InstanceFlagValidationIndirectCall             InstanceFlag = 0x00000020
	InstanceFlagAutomaticTimestampNormalization    InstanceFlag = 0x00000040
	InstanceFlagDefault                            InstanceFlag = 0x01000000
	InstanceFlagDebugging                          InstanceFlag = 0x02000000
	InstanceFlagAdvancedDebugging                  InstanceFlag = 0x04000000
	InstanceFlagWithEnv                            InstanceFlag = 0x08000000
)

func (v InstanceFlag) String() string {
	switch v {
	case InstanceFlagEmpty:
		return "empty"
	case InstanceFlagDebug:
		return "debug"
	case InstanceFlagValidation:
		return "validation"
	case InstanceFlagDiscardHalLabels:
		return "discard-hal-labels"
	case InstanceFlagAllowUnderlyingNoncompliantAdapter:
		return "allow-underlying-noncompliant-adapter"
	case InstanceFlagGPUBasedValidation:
		return "gpu-based-validation"
	case InstanceFlagValidationIndirectCall:
		return "validation-indirect-call"
	case InstanceFlagAutomaticTimestampNormalization:
		return "automatic-timestamp-normalization"
	case InstanceFlagDefault:
		return "default"
	case InstanceFlagDebugging:
		return "debugging"
	case InstanceFlagAdvancedDebugging:
		return "advanced-debugging"
	case InstanceFlagWithEnv:
		return "with-env"
	default:
		return ""
	}
}

type LoadOp uint32

const (
	LoadOpUndefined LoadOp = 0x00000000
	LoadOpLoad      LoadOp = 0x00000001
	LoadOpClear     LoadOp = 0x00000002
)

func (v LoadOp) String() string {
	switch v {
	case LoadOpUndefined:
		return "undefined"
	case LoadOpLoad:
		return "load"
	case LoadOpClear:
		return "clear"
	default:
		return ""
	}
}

type LogLevel uint32

const (
	LogLevelOff   LogLevel = 0x00000000
	LogLevelError LogLevel = 0x00000001
	LogLevelWarn  LogLevel = 0x00000002
	LogLevelInfo  LogLevel = 0x00000003
	LogLevelDebug LogLevel = 0x00000004
	LogLevelTrace LogLevel = 0x00000005
)

func (v LogLevel) String() string {
	switch v {
	case LogLevelOff:
		return "off"
	case LogLevelError:
		return "error"
	case LogLevelWarn:
		return "warn"
	case LogLevelInfo:
		return "info"
	case LogLevelDebug:
		return "debug"
	case LogLevelTrace:
		return "trace"
	default:
		return ""
	}
}

type MapAsyncStatus uint32

const (
	MapAsyncStatusSuccess           MapAsyncStatus = 0x00000001
	MapAsyncStatusCallbackCancelled MapAsyncStatus = 0x00000002
	MapAsyncStatusError             MapAsyncStatus = 0x00000003
	MapAsyncStatusAborted           MapAsyncStatus = 0x00000004
)

func (v MapAsyncStatus) String() string {
	switch v {
	case MapAsyncStatusSuccess:
		return "success"
	case MapAsyncStatusCallbackCancelled:
		return "callback-cancelled"
	case MapAsyncStatusError:
		return "error"
	case MapAsyncStatusAborted:
		return "aborted"
	default:
		return ""
	}
}

type MapMode uint32

const (
	MapModeNone  MapMode = 0x00000000
	MapModeRead  MapMode = 0x00000001
	MapModeWrite MapMode = 0x00000002
)

func (v MapMode) String() string {
	switch v {
	case MapModeNone:
		return "none"
	case MapModeRead:
		return "read"
	case MapModeWrite:
		return "write"
	default:
		return ""
	}
}

type MipmapFilterMode uint32

const (
	MipmapFilterModeUndefined MipmapFilterMode = 0x00000000
	MipmapFilterModeNearest   MipmapFilterMode = 0x00000001
	MipmapFilterModeLinear    MipmapFilterMode = 0x00000002
)

func (v MipmapFilterMode) String() string {
	switch v {
	case MipmapFilterModeUndefined:
		return "undefined"
	case MipmapFilterModeNearest:
		return "nearest"
	case MipmapFilterModeLinear:
		return "linear"
	default:
		return ""
	}
}

type NativeDisplayHandleType uint32

const (
	NativeDisplayHandleTypeNone    NativeDisplayHandleType = 0x00000000
	NativeDisplayHandleTypeXlib    NativeDisplayHandleType = 0x00000001
	NativeDisplayHandleTypeXcb     NativeDisplayHandleType = 0x00000002
	NativeDisplayHandleTypeWayland NativeDisplayHandleType = 0x00000003
)

func (v NativeDisplayHandleType) String() string {
	switch v {
	case NativeDisplayHandleTypeNone:
		return "none"
	case NativeDisplayHandleTypeXlib:
		return "xlib"
	case NativeDisplayHandleTypeXcb:
		return "xcb"
	case NativeDisplayHandleTypeWayland:
		return "wayland"
	default:
		return ""
	}
}

type NativeQueryType uint32

const NativeQueryTypePipelineStatistics NativeQueryType = 0x00030000

func (v NativeQueryType) String() string {
	switch v {
	case NativeQueryTypePipelineStatistics:
		return "pipeline-statistics"
	default:
		return ""
	}
}

type NativeTextureFormat uint32

const (
	NativeTextureFormatR16Unorm    NativeTextureFormat = 0x00030001
	NativeTextureFormatR16Snorm    NativeTextureFormat = 0x00030002
	NativeTextureFormatRg16Unorm   NativeTextureFormat = 0x00030003
	NativeTextureFormatRg16Snorm   NativeTextureFormat = 0x00030004
	NativeTextureFormatRgba16Unorm NativeTextureFormat = 0x00030005
	NativeTextureFormatRgba16Snorm NativeTextureFormat = 0x00030006
	NativeTextureFormatNV12        NativeTextureFormat = 0x00030007
	NativeTextureFormatP010        NativeTextureFormat = 0x00030008
)

func (v NativeTextureFormat) String() string {
	switch v {
	case NativeTextureFormatR16Unorm:
		return "r16-unorm"
	case NativeTextureFormatR16Snorm:
		return "r16-snorm"
	case NativeTextureFormatRg16Unorm:
		return "rg16-unorm"
	case NativeTextureFormatRg16Snorm:
		return "rg16-snorm"
	case NativeTextureFormatRgba16Unorm:
		return "rgba16-unorm"
	case NativeTextureFormatRgba16Snorm:
		return "rgba16-snorm"
	case NativeTextureFormatNV12:
		return "nv12"
	case NativeTextureFormatP010:
		return "p010"
	default:
		return ""
	}
}

type OptionalBool uint32

const (
	OptionalBoolFalse     OptionalBool = 0x00000000
	OptionalBoolTrue      OptionalBool = 0x00000001
	OptionalBoolUndefined OptionalBool = 0x00000002
)

func (v OptionalBool) String() string {
	switch v {
	case OptionalBoolFalse:
		return "false"
	case OptionalBoolTrue:
		return "true"
	case OptionalBoolUndefined:
		return "undefined"
	default:
		return ""
	}
}

type PipelineStatisticName uint32

const (
	PipelineStatisticNameVertexShaderInvocations   PipelineStatisticName = 0x00000000
	PipelineStatisticNameClipperInvocations        PipelineStatisticName = 0x00000001
	PipelineStatisticNameClipperPrimitivesOut      PipelineStatisticName = 0x00000002
	PipelineStatisticNameFragmentShaderInvocations PipelineStatisticName = 0x00000003
	PipelineStatisticNameComputeShaderInvocations  PipelineStatisticName = 0x00000004
)

func (v PipelineStatisticName) String() string {
	switch v {
	case PipelineStatisticNameVertexShaderInvocations:
		return "vertex-shader-invocations"
	case PipelineStatisticNameClipperInvocations:
		return "clipper-invocations"
	case PipelineStatisticNameClipperPrimitivesOut:
		return "clipper-primitives-out"
	case PipelineStatisticNameFragmentShaderInvocations:
		return "fragment-shader-invocations"
	case PipelineStatisticNameComputeShaderInvocations:
		return "compute-shader-invocations"
	default:
		return ""
	}
}

type PolygonMode uint32

const (
	PolygonModeFill  PolygonMode = 0x00000000
	PolygonModeLine  PolygonMode = 0x00000001
	PolygonModePoint PolygonMode = 0x00000002
)

func (v PolygonMode) String() string {
	switch v {
	case PolygonModeFill:
		return "fill"
	case PolygonModeLine:
		return "line"
	case PolygonModePoint:
		return "point"
	default:
		return ""
	}
}

type PopErrorScopeStatus uint32

const (
	PopErrorScopeStatusSuccess           PopErrorScopeStatus = 0x00000001
	PopErrorScopeStatusCallbackCancelled PopErrorScopeStatus = 0x00000002
	PopErrorScopeStatusError             PopErrorScopeStatus = 0x00000003
)

func (v PopErrorScopeStatus) String() string {
	switch v {
	case PopErrorScopeStatusSuccess:
		return "success"
	case PopErrorScopeStatusCallbackCancelled:
		return "callback-cancelled"
	case PopErrorScopeStatusError:
		return "error"
	default:
		return ""
	}
}

type PowerPreference uint32

const (
	PowerPreferenceUndefined       PowerPreference = 0x00000000
	PowerPreferenceLowPower        PowerPreference = 0x00000001
	PowerPreferenceHighPerformance PowerPreference = 0x00000002
)

func (v PowerPreference) String() string {
	switch v {
	case PowerPreferenceUndefined:
		return "undefined"
	case PowerPreferenceLowPower:
		return "low-power"
	case PowerPreferenceHighPerformance:
		return "high-performance"
	default:
		return ""
	}
}

type PredefinedColorSpace uint32

const (
	PredefinedColorSpaceSRGB      PredefinedColorSpace = 0x00000001
	PredefinedColorSpaceDisplayP3 PredefinedColorSpace = 0x00000002
)

func (v PredefinedColorSpace) String() string {
	switch v {
	case PredefinedColorSpaceSRGB:
		return "srgb"
	case PredefinedColorSpaceDisplayP3:
		return "display-p3"
	default:
		return ""
	}
}

type PresentMode uint32

const (
	PresentModeUndefined   PresentMode = 0x00000000
	PresentModeFifo        PresentMode = 0x00000001
	PresentModeFifoRelaxed PresentMode = 0x00000002
	PresentModeImmediate   PresentMode = 0x00000003
	PresentModeMailbox     PresentMode = 0x00000004
)

func (v PresentMode) String() string {
	switch v {
	case PresentModeUndefined:
		return "undefined"
	case PresentModeFifo:
		return "fifo"
	case PresentModeFifoRelaxed:
		return "fifo-relaxed"
	case PresentModeImmediate:
		return "immediate"
	case PresentModeMailbox:
		return "mailbox"
	default:
		return ""
	}
}

type PrimitiveTopology uint32

const (
	PrimitiveTopologyUndefined     PrimitiveTopology = 0x00000000
	PrimitiveTopologyPointList     PrimitiveTopology = 0x00000001
	PrimitiveTopologyLineList      PrimitiveTopology = 0x00000002
	PrimitiveTopologyLineStrip     PrimitiveTopology = 0x00000003
	PrimitiveTopologyTriangleList  PrimitiveTopology = 0x00000004
	PrimitiveTopologyTriangleStrip PrimitiveTopology = 0x00000005
)

func (v PrimitiveTopology) String() string {
	switch v {
	case PrimitiveTopologyUndefined:
		return "undefined"
	case PrimitiveTopologyPointList:
		return "point-list"
	case PrimitiveTopologyLineList:
		return "line-list"
	case PrimitiveTopologyLineStrip:
		return "line-strip"
	case PrimitiveTopologyTriangleList:
		return "triangle-list"
	case PrimitiveTopologyTriangleStrip:
		return "triangle-strip"
	default:
		return ""
	}
}

type QueryType uint32

const (
	QueryTypeOcclusion QueryType = 0x00000001
	QueryTypeTimestamp QueryType = 0x00000002
)

func (v QueryType) String() string {
	switch v {
	case QueryTypeOcclusion:
		return "occlusion"
	case QueryTypeTimestamp:
		return "timestamp"
	default:
		return ""
	}
}

type QueueWorkDoneStatus uint32

const (
	QueueWorkDoneStatusSuccess           QueueWorkDoneStatus = 0x00000001
	QueueWorkDoneStatusCallbackCancelled QueueWorkDoneStatus = 0x00000002
	QueueWorkDoneStatusError             QueueWorkDoneStatus = 0x00000003
)

func (v QueueWorkDoneStatus) String() string {
	switch v {
	case QueueWorkDoneStatusSuccess:
		return "success"
	case QueueWorkDoneStatusCallbackCancelled:
		return "callback-cancelled"
	case QueueWorkDoneStatusError:
		return "error"
	default:
		return ""
	}
}

type RequestAdapterStatus uint32

const (
	RequestAdapterStatusSuccess           RequestAdapterStatus = 0x00000001
	RequestAdapterStatusCallbackCancelled RequestAdapterStatus = 0x00000002
	RequestAdapterStatusUnavailable       RequestAdapterStatus = 0x00000003
	RequestAdapterStatusError             RequestAdapterStatus = 0x00000004
)

func (v RequestAdapterStatus) String() string {
	switch v {
	case RequestAdapterStatusSuccess:
		return "success"
	case RequestAdapterStatusCallbackCancelled:
		return "callback-cancelled"
	case RequestAdapterStatusUnavailable:
		return "unavailable"
	case RequestAdapterStatusError:
		return "error"
	default:
		return ""
	}
}

type RequestDeviceStatus uint32

const (
	RequestDeviceStatusSuccess           RequestDeviceStatus = 0x00000001
	RequestDeviceStatusCallbackCancelled RequestDeviceStatus = 0x00000002
	RequestDeviceStatusError             RequestDeviceStatus = 0x00000003
)

func (v RequestDeviceStatus) String() string {
	switch v {
	case RequestDeviceStatusSuccess:
		return "success"
	case RequestDeviceStatusCallbackCancelled:
		return "callback-cancelled"
	case RequestDeviceStatusError:
		return "error"
	default:
		return ""
	}
}

type SamplerBindingType uint32

const (
	SamplerBindingTypeBindingNotUsed SamplerBindingType = 0x00000000
	SamplerBindingTypeUndefined      SamplerBindingType = 0x00000001
	SamplerBindingTypeFiltering      SamplerBindingType = 0x00000002
	SamplerBindingTypeNonFiltering   SamplerBindingType = 0x00000003
	SamplerBindingTypeComparison     SamplerBindingType = 0x00000004
)

func (v SamplerBindingType) String() string {
	switch v {
	case SamplerBindingTypeBindingNotUsed:
		return "binding-not-used"
	case SamplerBindingTypeUndefined:
		return "undefined"
	case SamplerBindingTypeFiltering:
		return "filtering"
	case SamplerBindingTypeNonFiltering:
		return "non-filtering"
	case SamplerBindingTypeComparison:
		return "comparison"
	default:
		return ""
	}
}

type ShaderStage uint32

const (
	ShaderStageNone     ShaderStage = 0x00000000
	ShaderStageVertex   ShaderStage = 0x00000001
	ShaderStageFragment ShaderStage = 0x00000002
	ShaderStageCompute  ShaderStage = 0x00000004
)

func (v ShaderStage) String() string {
	switch v {
	case ShaderStageNone:
		return "none"
	case ShaderStageVertex:
		return "vertex"
	case ShaderStageFragment:
		return "fragment"
	case ShaderStageCompute:
		return "compute"
	default:
		return ""
	}
}

type Status uint32

const (
	StatusSuccess Status = 0x00000001
	StatusError   Status = 0x00000002
)

func (v Status) String() string {
	switch v {
	case StatusSuccess:
		return "success"
	case StatusError:
		return "error"
	default:
		return ""
	}
}

type StencilOperation uint32

const (
	StencilOperationUndefined      StencilOperation = 0x00000000
	StencilOperationKeep           StencilOperation = 0x00000001
	StencilOperationZero           StencilOperation = 0x00000002
	StencilOperationReplace        StencilOperation = 0x00000003
	StencilOperationInvert         StencilOperation = 0x00000004
	StencilOperationIncrementClamp StencilOperation = 0x00000005
	StencilOperationDecrementClamp StencilOperation = 0x00000006
	StencilOperationIncrementWrap  StencilOperation = 0x00000007
	StencilOperationDecrementWrap  StencilOperation = 0x00000008
)

func (v StencilOperation) String() string {
	switch v {
	case StencilOperationUndefined:
		return "undefined"
	case StencilOperationKeep:
		return "keep"
	case StencilOperationZero:
		return "zero"
	case StencilOperationReplace:
		return "replace"
	case StencilOperationInvert:
		return "invert"
	case StencilOperationIncrementClamp:
		return "increment-clamp"
	case StencilOperationDecrementClamp:
		return "decrement-clamp"
	case StencilOperationIncrementWrap:
		return "increment-wrap"
	case StencilOperationDecrementWrap:
		return "decrement-wrap"
	default:
		return ""
	}
}

type StorageTextureAccess uint32

const (
	StorageTextureAccessBindingNotUsed StorageTextureAccess = 0x00000000
	StorageTextureAccessUndefined      StorageTextureAccess = 0x00000001
	StorageTextureAccessWriteOnly      StorageTextureAccess = 0x00000002
	StorageTextureAccessReadOnly       StorageTextureAccess = 0x00000003
	StorageTextureAccessReadWrite      StorageTextureAccess = 0x00000004
)

func (v StorageTextureAccess) String() string {
	switch v {
	case StorageTextureAccessBindingNotUsed:
		return "binding-not-used"
	case StorageTextureAccessUndefined:
		return "undefined"
	case StorageTextureAccessWriteOnly:
		return "write-only"
	case StorageTextureAccessReadOnly:
		return "read-only"
	case StorageTextureAccessReadWrite:
		return "read-write"
	default:
		return ""
	}
}

type StoreOp uint32

const (
	StoreOpUndefined StoreOp = 0x00000000
	StoreOpStore     StoreOp = 0x00000001
	StoreOpDiscard   StoreOp = 0x00000002
)

func (v StoreOp) String() string {
	switch v {
	case StoreOpUndefined:
		return "undefined"
	case StoreOpStore:
		return "store"
	case StoreOpDiscard:
		return "discard"
	default:
		return ""
	}
}

type SurfaceGetCurrentTextureStatus uint32

const (
	SurfaceGetCurrentTextureStatusSuccessOptimal    SurfaceGetCurrentTextureStatus = 0x00000001
	SurfaceGetCurrentTextureStatusSuccessSuboptimal SurfaceGetCurrentTextureStatus = 0x00000002
	SurfaceGetCurrentTextureStatusTimeout           SurfaceGetCurrentTextureStatus = 0x00000003
	SurfaceGetCurrentTextureStatusOutdated          SurfaceGetCurrentTextureStatus = 0x00000004
	SurfaceGetCurrentTextureStatusLost              SurfaceGetCurrentTextureStatus = 0x00000005
	SurfaceGetCurrentTextureStatusError             SurfaceGetCurrentTextureStatus = 0x00000006
	SurfaceGetCurrentTextureStatusOccluded          SurfaceGetCurrentTextureStatus = 0x00030001
)

func (v SurfaceGetCurrentTextureStatus) String() string {
	switch v {
	case SurfaceGetCurrentTextureStatusSuccessOptimal:
		return "success-optimal"
	case SurfaceGetCurrentTextureStatusSuccessSuboptimal:
		return "success-suboptimal"
	case SurfaceGetCurrentTextureStatusTimeout:
		return "timeout"
	case SurfaceGetCurrentTextureStatusOutdated:
		return "outdated"
	case SurfaceGetCurrentTextureStatusLost:
		return "lost"
	case SurfaceGetCurrentTextureStatusError:
		return "error"
	case SurfaceGetCurrentTextureStatusOccluded:
		return "occluded"
	default:
		return ""
	}
}

type TextureAspect uint32

const (
	TextureAspectUndefined   TextureAspect = 0x00000000
	TextureAspectAll         TextureAspect = 0x00000001
	TextureAspectStencilOnly TextureAspect = 0x00000002
	TextureAspectDepthOnly   TextureAspect = 0x00000003
)

func (v TextureAspect) String() string {
	switch v {
	case TextureAspectUndefined:
		return "undefined"
	case TextureAspectAll:
		return "all"
	case TextureAspectStencilOnly:
		return "stencil-only"
	case TextureAspectDepthOnly:
		return "depth-only"
	default:
		return ""
	}
}

type TextureDimension uint32

const (
	TextureDimensionUndefined TextureDimension = 0x00000000
	TextureDimension1D        TextureDimension = 0x00000001
	TextureDimension2D        TextureDimension = 0x00000002
	TextureDimension3D        TextureDimension = 0x00000003
)

func (v TextureDimension) String() string {
	switch v {
	case TextureDimensionUndefined:
		return "undefined"
	case TextureDimension1D:
		return "1d"
	case TextureDimension2D:
		return "2d"
	case TextureDimension3D:
		return "3d"
	default:
		return ""
	}
}

type TextureFormat uint32

const (
	TextureFormatUndefined            TextureFormat = 0x00000000
	TextureFormatR8Unorm              TextureFormat = 0x00000001
	TextureFormatR8Snorm              TextureFormat = 0x00000002
	TextureFormatR8Uint               TextureFormat = 0x00000003
	TextureFormatR8Sint               TextureFormat = 0x00000004
	TextureFormatR16Unorm             TextureFormat = 0x00000005
	TextureFormatR16Snorm             TextureFormat = 0x00000006
	TextureFormatR16Uint              TextureFormat = 0x00000007
	TextureFormatR16Sint              TextureFormat = 0x00000008
	TextureFormatR16Float             TextureFormat = 0x00000009
	TextureFormatRG8Unorm             TextureFormat = 0x0000000A
	TextureFormatRG8Snorm             TextureFormat = 0x0000000B
	TextureFormatRG8Uint              TextureFormat = 0x0000000C
	TextureFormatRG8Sint              TextureFormat = 0x0000000D
	TextureFormatR32Float             TextureFormat = 0x0000000E
	TextureFormatR32Uint              TextureFormat = 0x0000000F
	TextureFormatR32Sint              TextureFormat = 0x00000010
	TextureFormatRG16Unorm            TextureFormat = 0x00000011
	TextureFormatRG16Snorm            TextureFormat = 0x00000012
	TextureFormatRG16Uint             TextureFormat = 0x00000013
	TextureFormatRG16Sint             TextureFormat = 0x00000014
	TextureFormatRG16Float            TextureFormat = 0x00000015
	TextureFormatRGBA8Unorm           TextureFormat = 0x00000016
	TextureFormatRGBA8UnormSrgb       TextureFormat = 0x00000017
	TextureFormatRGBA8Snorm           TextureFormat = 0x00000018
	TextureFormatRGBA8Uint            TextureFormat = 0x00000019
	TextureFormatRGBA8Sint            TextureFormat = 0x0000001A
	TextureFormatBGRA8Unorm           TextureFormat = 0x0000001B
	TextureFormatBGRA8UnormSrgb       TextureFormat = 0x0000001C
	TextureFormatRGB10A2Uint          TextureFormat = 0x0000001D
	TextureFormatRGB10A2Unorm         TextureFormat = 0x0000001E
	TextureFormatRG11B10Ufloat        TextureFormat = 0x0000001F
	TextureFormatRGB9E5Ufloat         TextureFormat = 0x00000020
	TextureFormatRG32Float            TextureFormat = 0x00000021
	TextureFormatRG32Uint             TextureFormat = 0x00000022
	TextureFormatRG32Sint             TextureFormat = 0x00000023
	TextureFormatRGBA16Unorm          TextureFormat = 0x00000024
	TextureFormatRGBA16Snorm          TextureFormat = 0x00000025
	TextureFormatRGBA16Uint           TextureFormat = 0x00000026
	TextureFormatRGBA16Sint           TextureFormat = 0x00000027
	TextureFormatRGBA16Float          TextureFormat = 0x00000028
	TextureFormatRGBA32Float          TextureFormat = 0x00000029
	TextureFormatRGBA32Uint           TextureFormat = 0x0000002A
	TextureFormatRGBA32Sint           TextureFormat = 0x0000002B
	TextureFormatStencil8             TextureFormat = 0x0000002C
	TextureFormatDepth16Unorm         TextureFormat = 0x0000002D
	TextureFormatDepth24Plus          TextureFormat = 0x0000002E
	TextureFormatDepth24PlusStencil8  TextureFormat = 0x0000002F
	TextureFormatDepth32Float         TextureFormat = 0x00000030
	TextureFormatDepth32FloatStencil8 TextureFormat = 0x00000031
	TextureFormatBC1RGBAUnorm         TextureFormat = 0x00000032
	TextureFormatBC1RGBAUnormSrgb     TextureFormat = 0x00000033
	TextureFormatBC2RGBAUnorm         TextureFormat = 0x00000034
	TextureFormatBC2RGBAUnormSrgb     TextureFormat = 0x00000035
	TextureFormatBC3RGBAUnorm         TextureFormat = 0x00000036
	TextureFormatBC3RGBAUnormSrgb     TextureFormat = 0x00000037
	TextureFormatBC4RUnorm            TextureFormat = 0x00000038
	TextureFormatBC4RSnorm            TextureFormat = 0x00000039
	TextureFormatBC5RGUnorm           TextureFormat = 0x0000003A
	TextureFormatBC5RGSnorm           TextureFormat = 0x0000003B
	TextureFormatBC6HRGBUfloat        TextureFormat = 0x0000003C
	TextureFormatBC6HRGBFloat         TextureFormat = 0x0000003D
	TextureFormatBC7RGBAUnorm         TextureFormat = 0x0000003E
	TextureFormatBC7RGBAUnormSrgb     TextureFormat = 0x0000003F
	TextureFormatETC2RGB8Unorm        TextureFormat = 0x00000040
	TextureFormatETC2RGB8UnormSrgb    TextureFormat = 0x00000041
	TextureFormatETC2RGB8A1Unorm      TextureFormat = 0x00000042
	TextureFormatETC2RGB8A1UnormSrgb  TextureFormat = 0x00000043
	TextureFormatETC2RGBA8Unorm       TextureFormat = 0x00000044
	TextureFormatETC2RGBA8UnormSrgb   TextureFormat = 0x00000045
	TextureFormatEACR11Unorm          TextureFormat = 0x00000046
	TextureFormatEACR11Snorm          TextureFormat = 0x00000047
	TextureFormatEACRG11Unorm         TextureFormat = 0x00000048
	TextureFormatEACRG11Snorm         TextureFormat = 0x00000049
	TextureFormatASTC4x4Unorm         TextureFormat = 0x0000004A
	TextureFormatASTC4x4UnormSrgb     TextureFormat = 0x0000004B
	TextureFormatASTC5x4Unorm         TextureFormat = 0x0000004C
	TextureFormatASTC5x4UnormSrgb     TextureFormat = 0x0000004D
	TextureFormatASTC5x5Unorm         TextureFormat = 0x0000004E
	TextureFormatASTC5x5UnormSrgb     TextureFormat = 0x0000004F
	TextureFormatASTC6x5Unorm         TextureFormat = 0x00000050
	TextureFormatASTC6x5UnormSrgb     TextureFormat = 0x00000051
	TextureFormatASTC6x6Unorm         TextureFormat = 0x00000052
	TextureFormatASTC6x6UnormSrgb     TextureFormat = 0x00000053
	TextureFormatASTC8x5Unorm         TextureFormat = 0x00000054
	TextureFormatASTC8x5UnormSrgb     TextureFormat = 0x00000055
	TextureFormatASTC8x6Unorm         TextureFormat = 0x00000056
	TextureFormatASTC8x6UnormSrgb     TextureFormat = 0x00000057
	TextureFormatASTC8x8Unorm         TextureFormat = 0x00000058
	TextureFormatASTC8x8UnormSrgb     TextureFormat = 0x00000059
	TextureFormatASTC10x5Unorm        TextureFormat = 0x0000005A
	TextureFormatASTC10x5UnormSrgb    TextureFormat = 0x0000005B
	TextureFormatASTC10x6Unorm        TextureFormat = 0x0000005C
	TextureFormatASTC10x6UnormSrgb    TextureFormat = 0x0000005D
	TextureFormatASTC10x8Unorm        TextureFormat = 0x0000005E
	TextureFormatASTC10x8UnormSrgb    TextureFormat = 0x0000005F
	TextureFormatASTC10x10Unorm       TextureFormat = 0x00000060
	TextureFormatASTC10x10UnormSrgb   TextureFormat = 0x00000061
	TextureFormatASTC12x10Unorm       TextureFormat = 0x00000062
	TextureFormatASTC12x10UnormSrgb   TextureFormat = 0x00000063
	TextureFormatASTC12x12Unorm       TextureFormat = 0x00000064
	TextureFormatASTC12x12UnormSrgb   TextureFormat = 0x00000065
)

func (v TextureFormat) String() string {
	switch v {
	case TextureFormatUndefined:
		return "undefined"
	case TextureFormatR8Unorm:
		return "r8-unorm"
	case TextureFormatR8Snorm:
		return "r8-snorm"
	case TextureFormatR8Uint:
		return "r8-uint"
	case TextureFormatR8Sint:
		return "r8-sint"
	case TextureFormatR16Unorm:
		return "r16-unorm"
	case TextureFormatR16Snorm:
		return "r16-snorm"
	case TextureFormatR16Uint:
		return "r16-uint"
	case TextureFormatR16Sint:
		return "r16-sint"
	case TextureFormatR16Float:
		return "r16-float"
	case TextureFormatRG8Unorm:
		return "rg8-unorm"
	case TextureFormatRG8Snorm:
		return "rg8-snorm"
	case TextureFormatRG8Uint:
		return "rg8-uint"
	case TextureFormatRG8Sint:
		return "rg8-sint"
	case TextureFormatR32Float:
		return "r32-float"
	case TextureFormatR32Uint:
		return "r32-uint"
	case TextureFormatR32Sint:
		return "r32-sint"
	case TextureFormatRG16Unorm:
		return "rg16-unorm"
	case TextureFormatRG16Snorm:
		return "rg16-snorm"
	case TextureFormatRG16Uint:
		return "rg16-uint"
	case TextureFormatRG16Sint:
		return "rg16-sint"
	case TextureFormatRG16Float:
		return "rg16-float"
	case TextureFormatRGBA8Unorm:
		return "rgba8-unorm"
	case TextureFormatRGBA8UnormSrgb:
		return "rgba8-unorm-srgb"
	case TextureFormatRGBA8Snorm:
		return "rgba8-snorm"
	case TextureFormatRGBA8Uint:
		return "rgba8-uint"
	case TextureFormatRGBA8Sint:
		return "rgba8-sint"
	case TextureFormatBGRA8Unorm:
		return "bgra8-unorm"
	case TextureFormatBGRA8UnormSrgb:
		return "bgra8-unorm-srgb"
	case TextureFormatRGB10A2Uint:
		return "rgb10a2-uint"
	case TextureFormatRGB10A2Unorm:
		return "rgb10a2-unorm"
	case TextureFormatRG11B10Ufloat:
		return "rg11b10-ufloat"
	case TextureFormatRGB9E5Ufloat:
		return "rgb9e5-ufloat"
	case TextureFormatRG32Float:
		return "rg32-float"
	case TextureFormatRG32Uint:
		return "rg32-uint"
	case TextureFormatRG32Sint:
		return "rg32-sint"
	case TextureFormatRGBA16Unorm:
		return "rgba16-unorm"
	case TextureFormatRGBA16Snorm:
		return "rgba16-snorm"
	case TextureFormatRGBA16Uint:
		return "rgba16-uint"
	case TextureFormatRGBA16Sint:
		return "rgba16-sint"
	case TextureFormatRGBA16Float:
		return "rgba16-float"
	case TextureFormatRGBA32Float:
		return "rgba32-float"
	case TextureFormatRGBA32Uint:
		return "rgba32-uint"
	case TextureFormatRGBA32Sint:
		return "rgba32-sint"
	case TextureFormatStencil8:
		return "stencil8"
	case TextureFormatDepth16Unorm:
		return "depth16-unorm"
	case TextureFormatDepth24Plus:
		return "depth24-plus"
	case TextureFormatDepth24PlusStencil8:
		return "depth24-plus-stencil8"
	case TextureFormatDepth32Float:
		return "depth32-float"
	case TextureFormatDepth32FloatStencil8:
		return "depth32-float-stencil8"
	case TextureFormatBC1RGBAUnorm:
		return "bc1rgba-unorm"
	case TextureFormatBC1RGBAUnormSrgb:
		return "bc1rgba-unorm-srgb"
	case TextureFormatBC2RGBAUnorm:
		return "bc2rgba-unorm"
	case TextureFormatBC2RGBAUnormSrgb:
		return "bc2rgba-unorm-srgb"
	case TextureFormatBC3RGBAUnorm:
		return "bc3rgba-unorm"
	case TextureFormatBC3RGBAUnormSrgb:
		return "bc3rgba-unorm-srgb"
	case TextureFormatBC4RUnorm:
		return "bc4r-unorm"
	case TextureFormatBC4RSnorm:
		return "bc4r-snorm"
	case TextureFormatBC5RGUnorm:
		return "bc5rg-unorm"
	case TextureFormatBC5RGSnorm:
		return "bc5rg-snorm"
	case TextureFormatBC6HRGBUfloat:
		return "bc6hrgb-ufloat"
	case TextureFormatBC6HRGBFloat:
		return "bc6hrgb-float"
	case TextureFormatBC7RGBAUnorm:
		return "bc7rgba-unorm"
	case TextureFormatBC7RGBAUnormSrgb:
		return "bc7rgba-unorm-srgb"
	case TextureFormatETC2RGB8Unorm:
		return "etc2rgb8-unorm"
	case TextureFormatETC2RGB8UnormSrgb:
		return "etc2rgb8-unorm-srgb"
	case TextureFormatETC2RGB8A1Unorm:
		return "etc2rgb8a1-unorm"
	case TextureFormatETC2RGB8A1UnormSrgb:
		return "etc2rgb8a1-unorm-srgb"
	case TextureFormatETC2RGBA8Unorm:
		return "etc2rgba8-unorm"
	case TextureFormatETC2RGBA8UnormSrgb:
		return "etc2rgba8-unorm-srgb"
	case TextureFormatEACR11Unorm:
		return "eacr11-unorm"
	case TextureFormatEACR11Snorm:
		return "eacr11-snorm"
	case TextureFormatEACRG11Unorm:
		return "eacrg11-unorm"
	case TextureFormatEACRG11Snorm:
		return "eacrg11-snorm"
	case TextureFormatASTC4x4Unorm:
		return "astc4x4-unorm"
	case TextureFormatASTC4x4UnormSrgb:
		return "astc4x4-unorm-srgb"
	case TextureFormatASTC5x4Unorm:
		return "astc5x4-unorm"
	case TextureFormatASTC5x4UnormSrgb:
		return "astc5x4-unorm-srgb"
	case TextureFormatASTC5x5Unorm:
		return "astc5x5-unorm"
	case TextureFormatASTC5x5UnormSrgb:
		return "astc5x5-unorm-srgb"
	case TextureFormatASTC6x5Unorm:
		return "astc6x5-unorm"
	case TextureFormatASTC6x5UnormSrgb:
		return "astc6x5-unorm-srgb"
	case TextureFormatASTC6x6Unorm:
		return "astc6x6-unorm"
	case TextureFormatASTC6x6UnormSrgb:
		return "astc6x6-unorm-srgb"
	case TextureFormatASTC8x5Unorm:
		return "astc8x5-unorm"
	case TextureFormatASTC8x5UnormSrgb:
		return "astc8x5-unorm-srgb"
	case TextureFormatASTC8x6Unorm:
		return "astc8x6-unorm"
	case TextureFormatASTC8x6UnormSrgb:
		return "astc8x6-unorm-srgb"
	case TextureFormatASTC8x8Unorm:
		return "astc8x8-unorm"
	case TextureFormatASTC8x8UnormSrgb:
		return "astc8x8-unorm-srgb"
	case TextureFormatASTC10x5Unorm:
		return "astc10x5-unorm"
	case TextureFormatASTC10x5UnormSrgb:
		return "astc10x5-unorm-srgb"
	case TextureFormatASTC10x6Unorm:
		return "astc10x6-unorm"
	case TextureFormatASTC10x6UnormSrgb:
		return "astc10x6-unorm-srgb"
	case TextureFormatASTC10x8Unorm:
		return "astc10x8-unorm"
	case TextureFormatASTC10x8UnormSrgb:
		return "astc10x8-unorm-srgb"
	case TextureFormatASTC10x10Unorm:
		return "astc10x10-unorm"
	case TextureFormatASTC10x10UnormSrgb:
		return "astc10x10-unorm-srgb"
	case TextureFormatASTC12x10Unorm:
		return "astc12x10-unorm"
	case TextureFormatASTC12x10UnormSrgb:
		return "astc12x10-unorm-srgb"
	case TextureFormatASTC12x12Unorm:
		return "astc12x12-unorm"
	case TextureFormatASTC12x12UnormSrgb:
		return "astc12x12-unorm-srgb"
	default:
		return ""
	}
}

type TextureSampleType uint32

const (
	TextureSampleTypeBindingNotUsed    TextureSampleType = 0x00000000
	TextureSampleTypeUndefined         TextureSampleType = 0x00000001
	TextureSampleTypeFloat             TextureSampleType = 0x00000002
	TextureSampleTypeUnfilterableFloat TextureSampleType = 0x00000003
	TextureSampleTypeDepth             TextureSampleType = 0x00000004
	TextureSampleTypeSint              TextureSampleType = 0x00000005
	TextureSampleTypeUint              TextureSampleType = 0x00000006
)

func (v TextureSampleType) String() string {
	switch v {
	case TextureSampleTypeBindingNotUsed:
		return "binding-not-used"
	case TextureSampleTypeUndefined:
		return "undefined"
	case TextureSampleTypeFloat:
		return "float"
	case TextureSampleTypeUnfilterableFloat:
		return "unfilterable-float"
	case TextureSampleTypeDepth:
		return "depth"
	case TextureSampleTypeSint:
		return "sint"
	case TextureSampleTypeUint:
		return "uint"
	default:
		return ""
	}
}

type TextureUsage uint32

const (
	TextureUsageNone                TextureUsage = 0x00000000
	TextureUsageCopySrc             TextureUsage = 0x00000001
	TextureUsageCopyDst             TextureUsage = 0x00000002
	TextureUsageTextureBinding      TextureUsage = 0x00000004
	TextureUsageStorageBinding      TextureUsage = 0x00000008
	TextureUsageRenderAttachment    TextureUsage = 0x00000010
	TextureUsageTransientAttachment TextureUsage = 0x00000020
)

func (v TextureUsage) String() string {
	switch v {
	case TextureUsageNone:
		return "none"
	case TextureUsageCopySrc:
		return "copy-src"
	case TextureUsageCopyDst:
		return "copy-dst"
	case TextureUsageTextureBinding:
		return "texture-binding"
	case TextureUsageStorageBinding:
		return "storage-binding"
	case TextureUsageRenderAttachment:
		return "render-attachment"
	case TextureUsageTransientAttachment:
		return "transient-attachment"
	default:
		return ""
	}
}

type TextureViewDimension uint32

const (
	TextureViewDimensionUndefined TextureViewDimension = 0x00000000
	TextureViewDimension1D        TextureViewDimension = 0x00000001
	TextureViewDimension2D        TextureViewDimension = 0x00000002
	TextureViewDimension2DArray   TextureViewDimension = 0x00000003
	TextureViewDimensionCube      TextureViewDimension = 0x00000004
	TextureViewDimensionCubeArray TextureViewDimension = 0x00000005
	TextureViewDimension3D        TextureViewDimension = 0x00000006
)

func (v TextureViewDimension) String() string {
	switch v {
	case TextureViewDimensionUndefined:
		return "undefined"
	case TextureViewDimension1D:
		return "1d"
	case TextureViewDimension2D:
		return "2d"
	case TextureViewDimension2DArray:
		return "2d-array"
	case TextureViewDimensionCube:
		return "cube"
	case TextureViewDimensionCubeArray:
		return "cube-array"
	case TextureViewDimension3D:
		return "3d"
	default:
		return ""
	}
}

type ToneMappingMode uint32

const (
	ToneMappingModeStandard ToneMappingMode = 0x00000001
	ToneMappingModeExtended ToneMappingMode = 0x00000002
)

func (v ToneMappingMode) String() string {
	switch v {
	case ToneMappingModeStandard:
		return "standard"
	case ToneMappingModeExtended:
		return "extended"
	default:
		return ""
	}
}

type VertexFormat uint32

const (
	VertexFormatUint8        VertexFormat = 0x00000001
	VertexFormatUint8x2      VertexFormat = 0x00000002
	VertexFormatUint8x4      VertexFormat = 0x00000003
	VertexFormatSint8        VertexFormat = 0x00000004
	VertexFormatSint8x2      VertexFormat = 0x00000005
	VertexFormatSint8x4      VertexFormat = 0x00000006
	VertexFormatUnorm8       VertexFormat = 0x00000007
	VertexFormatUnorm8x2     VertexFormat = 0x00000008
	VertexFormatUnorm8x4     VertexFormat = 0x00000009
	VertexFormatSnorm8       VertexFormat = 0x0000000A
	VertexFormatSnorm8x2     VertexFormat = 0x0000000B
	VertexFormatSnorm8x4     VertexFormat = 0x0000000C
	VertexFormatUint16       VertexFormat = 0x0000000D
	VertexFormatUint16x2     VertexFormat = 0x0000000E
	VertexFormatUint16x4     VertexFormat = 0x0000000F
	VertexFormatSint16       VertexFormat = 0x00000010
	VertexFormatSint16x2     VertexFormat = 0x00000011
	VertexFormatSint16x4     VertexFormat = 0x00000012
	VertexFormatUnorm16      VertexFormat = 0x00000013
	VertexFormatUnorm16x2    VertexFormat = 0x00000014
	VertexFormatUnorm16x4    VertexFormat = 0x00000015
	VertexFormatSnorm16      VertexFormat = 0x00000016
	VertexFormatSnorm16x2    VertexFormat = 0x00000017
	VertexFormatSnorm16x4    VertexFormat = 0x00000018
	VertexFormatFloat16      VertexFormat = 0x00000019
	VertexFormatFloat16x2    VertexFormat = 0x0000001A
	VertexFormatFloat16x4    VertexFormat = 0x0000001B
	VertexFormatFloat32      VertexFormat = 0x0000001C
	VertexFormatFloat32x2    VertexFormat = 0x0000001D
	VertexFormatFloat32x3    VertexFormat = 0x0000001E
	VertexFormatFloat32x4    VertexFormat = 0x0000001F
	VertexFormatUint32       VertexFormat = 0x00000020
	VertexFormatUint32x2     VertexFormat = 0x00000021
	VertexFormatUint32x3     VertexFormat = 0x00000022
	VertexFormatUint32x4     VertexFormat = 0x00000023
	VertexFormatSint32       VertexFormat = 0x00000024
	VertexFormatSint32x2     VertexFormat = 0x00000025
	VertexFormatSint32x3     VertexFormat = 0x00000026
	VertexFormatSint32x4     VertexFormat = 0x00000027
	VertexFormatUnorm1010102 VertexFormat = 0x00000028
	VertexFormatUnorm8x4BGRA VertexFormat = 0x00000029
)

func (v VertexFormat) String() string {
	switch v {
	case VertexFormatUint8:
		return "uint8"
	case VertexFormatUint8x2:
		return "uint8x2"
	case VertexFormatUint8x4:
		return "uint8x4"
	case VertexFormatSint8:
		return "sint8"
	case VertexFormatSint8x2:
		return "sint8x2"
	case VertexFormatSint8x4:
		return "sint8x4"
	case VertexFormatUnorm8:
		return "unorm8"
	case VertexFormatUnorm8x2:
		return "unorm8x2"
	case VertexFormatUnorm8x4:
		return "unorm8x4"
	case VertexFormatSnorm8:
		return "snorm8"
	case VertexFormatSnorm8x2:
		return "snorm8x2"
	case VertexFormatSnorm8x4:
		return "snorm8x4"
	case VertexFormatUint16:
		return "uint16"
	case VertexFormatUint16x2:
		return "uint16x2"
	case VertexFormatUint16x4:
		return "uint16x4"
	case VertexFormatSint16:
		return "sint16"
	case VertexFormatSint16x2:
		return "sint16x2"
	case VertexFormatSint16x4:
		return "sint16x4"
	case VertexFormatUnorm16:
		return "unorm16"
	case VertexFormatUnorm16x2:
		return "unorm16x2"
	case VertexFormatUnorm16x4:
		return "unorm16x4"
	case VertexFormatSnorm16:
		return "snorm16"
	case VertexFormatSnorm16x2:
		return "snorm16x2"
	case VertexFormatSnorm16x4:
		return "snorm16x4"
	case VertexFormatFloat16:
		return "float16"
	case VertexFormatFloat16x2:
		return "float16x2"
	case VertexFormatFloat16x4:
		return "float16x4"
	case VertexFormatFloat32:
		return "float32"
	case VertexFormatFloat32x2:
		return "float32x2"
	case VertexFormatFloat32x3:
		return "float32x3"
	case VertexFormatFloat32x4:
		return "float32x4"
	case VertexFormatUint32:
		return "uint32"
	case VertexFormatUint32x2:
		return "uint32x2"
	case VertexFormatUint32x3:
		return "uint32x3"
	case VertexFormatUint32x4:
		return "uint32x4"
	case VertexFormatSint32:
		return "sint32"
	case VertexFormatSint32x2:
		return "sint32x2"
	case VertexFormatSint32x3:
		return "sint32x3"
	case VertexFormatSint32x4:
		return "sint32x4"
	case VertexFormatUnorm1010102:
		return "unorm1010102"
	case VertexFormatUnorm8x4BGRA:
		return "unorm8x4bgra"
	default:
		return ""
	}
}

type VertexStepMode uint32

const (
	VertexStepModeUndefined VertexStepMode = 0x00000000
	VertexStepModeVertex    VertexStepMode = 0x00000001
	VertexStepModeInstance  VertexStepMode = 0x00000002
)

func (v VertexStepMode) String() string {
	switch v {
	case VertexStepModeUndefined:
		return "undefined"
	case VertexStepModeVertex:
		return "vertex"
	case VertexStepModeInstance:
		return "instance"
	default:
		return ""
	}
}

type WGSLLanguageFeatureName uint32

const (
	WGSLLanguageFeatureNameReadonlyAndReadwriteStorageTextures WGSLLanguageFeatureName = 0x00000001
	WGSLLanguageFeatureNamePacked4x8IntegerDotProduct          WGSLLanguageFeatureName = 0x00000002
	WGSLLanguageFeatureNameUnrestrictedPointerParameters       WGSLLanguageFeatureName = 0x00000003
	WGSLLanguageFeatureNamePointerCompositeAccess              WGSLLanguageFeatureName = 0x00000004
	WGSLLanguageFeatureNameUniformBufferStandardLayout         WGSLLanguageFeatureName = 0x00000005
	WGSLLanguageFeatureNameSubgroupId                          WGSLLanguageFeatureName = 0x00000006
	WGSLLanguageFeatureNameTextureAndSamplerLet                WGSLLanguageFeatureName = 0x00000007
	WGSLLanguageFeatureNameSubgroupUniformity                  WGSLLanguageFeatureName = 0x00000008
	WGSLLanguageFeatureNameTextureFormatsTier1                 WGSLLanguageFeatureName = 0x00000009
)

func (v WGSLLanguageFeatureName) String() string {
	switch v {
	case WGSLLanguageFeatureNameReadonlyAndReadwriteStorageTextures:
		return "readonly-and-readwrite-storage-textures"
	case WGSLLanguageFeatureNamePacked4x8IntegerDotProduct:
		return "packed4x8-integer-dot-product"
	case WGSLLanguageFeatureNameUnrestrictedPointerParameters:
		return "unrestricted-pointer-parameters"
	case WGSLLanguageFeatureNamePointerCompositeAccess:
		return "pointer-composite-access"
	case WGSLLanguageFeatureNameUniformBufferStandardLayout:
		return "uniform-buffer-standard-layout"
	case WGSLLanguageFeatureNameSubgroupId:
		return "subgroup-id"
	case WGSLLanguageFeatureNameTextureAndSamplerLet:
		return "texture-and-sampler-let"
	case WGSLLanguageFeatureNameSubgroupUniformity:
		return "subgroup-uniformity"
	case WGSLLanguageFeatureNameTextureFormatsTier1:
		return "texture-formats-tier1"
	default:
		return ""
	}
}

type WaitStatus uint32

const (
	WaitStatusSuccess  WaitStatus = 0x00000001
	WaitStatusTimedOut WaitStatus = 0x00000002
	WaitStatusError    WaitStatus = 0x00000003
)

func (v WaitStatus) String() string {
	switch v {
	case WaitStatusSuccess:
		return "success"
	case WaitStatusTimedOut:
		return "timed-out"
	case WaitStatusError:
		return "error"
	default:
		return ""
	}
}
