#!/usr/bin/env python3
"""Regenerate wgpu/enums.go from wgpu/lib/webgpu.h + wgpu/lib/wgpu.h."""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

SKIP_TYPES = {"SType", "NativeSType"}
MERGE_TYPES = {"NativeFeature": "FeatureName"}

ENUM_RE = re.compile(
    r"typedef enum (WGPU\w+)\s*\{(.*?)\} \1(?: WGPU_ENUM_ATTRIBUTE)?;",
    re.S,
)
FLAG_TYPEDEF_RE = re.compile(r"typedef WGPUFlags (WGPU\w+);")
FLAG_CONST_RE = re.compile(
    r"static const (WGPU\w+) (\w+)\s*=\s*([^;]+);",
)


def to_kebab(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch == "-":
            prev_d = i > 0 and name[i - 1].isdigit()
            next_d = i < len(name) - 1 and name[i + 1].isdigit()
            if prev_d or next_d:
                continue
        if ch.isupper() and i > 0 and (name[i - 1].islower() or (i < len(name) - 1 and name[i + 1].islower())):
            out.append("-")
            out.append(ch.lower())
        elif ch == "_":
            out.append("-")
        else:
            out.append(ch.lower())
    return "".join(out)


def eval_c_int(expr: str) -> int:
    expr = re.sub(r"/\*.*?\*/", "", expr, flags=re.S)
    expr = expr.strip()
    if expr.startswith("0x") or expr.startswith("0X"):
        return int(expr, 16)
    if re.fullmatch(r"-?\d+", expr):
        return int(expr)
    expr = re.sub(r"\b(\d+)\s*<<\s*(\d+)\b", lambda m: str(int(m.group(1)) << int(m.group(2))), expr)
    expr = re.sub(r"\(([^()]+)\)", r"\1", expr)
    parts = [p.strip() for p in expr.split("|")]
    return sum(int(p) for p in parts)


def go_name_from_c(c_name: str) -> tuple[str, str]:
    key = c_name.removeprefix("WGPU")
    parts = key.split("_")
    typ = parts[0]
    if typ in SKIP_TYPES:
        return "", ""
    if typ in MERGE_TYPES:
        typ = MERGE_TYPES[typ]
        key = key.replace("NativeFeature", "FeatureName", 1)
    return typ, key.replace("_", "")


def parse_enums(header: str) -> dict[str, list[tuple[str, int]]]:
    groups: dict[str, list[tuple[str, int]]] = defaultdict(list)
    for m in ENUM_RE.finditer(header):
        body = m.group(2)
        for line in body.splitlines():
            line = line.strip()
            if not line or line.startswith("/*") or line.startswith("*"):
                continue
            mm = re.match(r"(\w+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)", line)
            if not mm:
                continue
            c_name, raw_val = mm.group(1), mm.group(2)
            if c_name.endswith("_Force32"):
                continue
            typ, go_name = go_name_from_c(c_name)
            if not typ:
                continue
            val = int(raw_val, 0)
            groups[typ].append((go_name, val))
    return groups


def parse_flags(header: str) -> dict[str, list[tuple[str, int]]]:
    groups: dict[str, list[tuple[str, int]]] = defaultdict(list)
    flag_types = {m.group(1) for m in FLAG_TYPEDEF_RE.finditer(header)}
    for m in FLAG_CONST_RE.finditer(header):
        flag_type, c_name, expr = m.group(1), m.group(2), m.group(3)
        if flag_type not in flag_types:
            continue
        if c_name.endswith("_Force32"):
            continue
        typ, go_name = go_name_from_c(c_name)
        if not typ:
            continue
        groups[typ].append((go_name, eval_c_int(expr)))
    return groups


def merge_groups(*sources: dict[str, list[tuple[str, int]]]) -> dict[str, list[tuple[str, int]]]:
    merged: dict[str, dict[str, int]] = defaultdict(dict)
    for src in sources:
        for typ, items in src.items():
            for go_name, val in items:
                merged[typ][go_name] = val
    out: dict[str, list[tuple[str, int]]] = {}
    for typ in sorted(merged):
        out[typ] = sorted(merged[typ].items(), key=lambda x: x[1])
    return out


def generate(groups: dict[str, list[tuple[str, int]]], pkg: str) -> str:
    lines = [
        "// Code generated by github.com/openfluke/webgpu/cmd/enums/regen.py; DO NOT EDIT.",
        "",
        f"package {pkg}",
        "",
    ]
    for typ, items in groups.items():
        lines.append(f"type {typ} uint32")
        lines.append("")
        if len(items) > 1:
            lines.append("const (")
            for go_name, val in items:
                lines.append(f"\t{go_name} {typ} = 0x{val:08X}")
            lines.append(")")
        elif items:
            go_name, val = items[0]
            lines.append(f"const {go_name} {typ} = 0x{val:08X}")
        lines.append("")
        lines.append(f"func (v {typ}) String() string {{")
        lines.append("\tswitch v {")
        seen_vals: set[int] = set()
        for go_name, val in items:
            if val in seen_vals:
                continue
            seen_vals.add(val)
            suffix = go_name[len(typ) :]
            lines.append(f"\tcase {go_name}:")
            lines.append(f'\t\treturn "{to_kebab(suffix)}"')
        if typ == "ErrorType":
            lines.append("\tdefault:")
            lines.append('\t\treturn "unknown"')
        else:
            lines.append("\tdefault:")
            lines.append('\t\treturn ""')
        lines.append("\t}")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def format_go(path: Path) -> None:
    if shutil.which("gofumpt"):
        subprocess.run(["gofumpt", "-w", str(path)], check=False)
        return
    subprocess.run(
        ["go", "run", "mvdan.cc/gofumpt@v0.6.0", "-w", str(path)],
        cwd=path.parents[1],
        check=False,
    )


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    headers = [root / "wgpu/lib/webgpu.h", root / "wgpu/lib/wgpu.h"]
    out_path = root / "wgpu/enums.go"
    if len(sys.argv) > 1:
        headers = [Path(p) for p in sys.argv[1:-1]] if len(sys.argv) > 2 else [Path(sys.argv[1])]
    if len(sys.argv) >= 2 and Path(sys.argv[-1]).suffix == ".go":
        out_path = Path(sys.argv[-1])

    text = "\n".join(h.read_text() for h in headers)
    groups = merge_groups(parse_enums(text), parse_flags(text))
    out_path.write_text(generate(groups, "wgpu"))
    format_go(out_path)
    print(f"wrote {out_path} ({len(groups)} enum types)")


if __name__ == "__main__":
    main()
